resources:
  - name: gitResource
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: shiptest-bt/ymlTest

pipelines: 
  - name: state_test_git
    steps:
      - name: testReport_u18
        type: Bash
        configuration:
          inputResources:
            - name: gitResource
        execution:
          onExecute:
            - pushd $res_gitResource_resourcePath
            - sudo chmod +x echoTest.sh
            - ./echoTest.sh
      
      - name: run_file_restore
        type: Bash
        configuration:
          inputSteps:
            - name: testReport_u18
        execution:
          onExecute:
            - printenv
